/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.exception.RegraNegocioException;
import javax.swing.JOptionPane;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author User
 */

@Component
@Scope("prototype")
@Slf4j
public class AdicionarCursoUI extends javax.swing.JDialog {
    
    private final CursoIController controller;
    private TelaCursosUI telaPrincipal;
    
    /**
     * Creates new form AdicionarCursoUI
     * @param controller
     */
    @Autowired
    public AdicionarCursoUI(CursoIController controller) {
        super((java.awt.Frame) null, false);
        this.controller = controller;
        log.info("Renderizando tela de adição de cursos");
        initComponents();
    }
    
    public void abrir(java.awt.Frame parent, boolean modal) {
        this.telaPrincipal = (TelaCursosUI) parent;
        setModal(modal);
        setSize(250, 300);  // Ajuste esses valores para caber todo seu conteúdo
        setLocationRelativeTo(parent);
        setVisible(true);
    }
    
    private void salvarCurso() {
        String nome = txtNome.getText().trim();
        String prof = txtProfessor.getText().trim();
        
        int carga;
        try {  
            carga = Integer.parseInt(txtCargaHoraria.getText().trim());   
        } catch (NumberFormatException ex) {
            log.error("Erro de formatação: cargaHorario inválida");
            carga = -1;
        }
        
        // Montando o objeto curso
        Curso curso = new Curso(nome, carga, prof);

        try {
            if (controller.save(curso)) {
                    telaPrincipal.carregarCursos();
                    log.info("Curso salvo com sucesso, fechando janela...");
                    dispose();
                }
        } catch (RegraNegocioException e) {
                 log.error("Erro de validação");
                 JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de validação", JOptionPane.ERROR_MESSAGE);
        }
 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCargaHoraria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProfessor = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADICIONAR CURSO");
        setModal(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 50, 30);

        jLabel2.setText("Carga Horaria ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 90, 30);

        txtCargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaHorariaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCargaHoraria);
        txtCargaHoraria.setBounds(130, 90, 80, 30);

        jLabel3.setText("Professor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 60, 30);
        getContentPane().add(txtProfessor);
        txtProfessor.setBounds(130, 150, 80, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(130, 30, 80, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 0, 0);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 30, 20);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 230, 50, 30);

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(80, 210, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaHorariaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarCurso();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProfessor;
    // End of variables declaration//GEN-END:variables
}
