/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.exception.RegraNegocioException;
import br.com.ifba.util.MensagemUtils;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author User
 */

@Component
@Scope("prototype")
@Slf4j
public class EditarCursoUI extends javax.swing.JDialog {
    
    private Curso curso;
    private final CursoIController controller;
    private TelaCursosUI telaPrincipal;
    
    

    /**
     * Creates new form AdicionarCursoUI
     * 
     * @param controller
     */
    @Autowired  
    public EditarCursoUI(CursoController controller) {
        super((java.awt.Frame) null, false); // Chama o construtor do JDialog sem pai e modal falso
        this.controller = controller;
        log.info("Renderizando tela de edição");
        initComponents();
    }

    
    public void abrir(java.awt.Frame parent, Curso curso, boolean modal) {
        this.curso = curso;
        this.telaPrincipal = (TelaCursosUI) parent;

        txtNomeAnt.setText(curso.getNome());
        txtCgAnt.setText(String.valueOf(curso.getCargaHoraria()));
        txtProfessorAnt.setText(curso.getProfessor());
        
        setModal(modal);
        setSize(400, 300);  // Ajuste esses valores para caber todo seu conteúdo
        setLocationRelativeTo(parent);
        setVisible(true);
    }
    
     private void salvarAlteracoes() {
        
        //trim() garante que " " seja "", tornando possivel detectar vazio
        String nome = txtNomeProx.getText().trim();
        String cargaTxt = txtCgProx.getText().trim();
        String professor = txtProfessorProx.getText().trim();

        int cargaHoraria;
        try {
            cargaHoraria = Integer.parseInt(cargaTxt);
        } catch (NumberFormatException ex) {
            log.error("Erro de formatação: cargaHoraria inválida");
            cargaHoraria = -1; // será validado na camada de serviço
        }
        
        // Monta o objeto
        curso.setNome(nome);
        curso.setCargaHoraria(cargaHoraria);
        curso.setProfessor(professor);        
        
        try {
            boolean sucesso = controller.save(curso);
            if (!sucesso) {
                log.error("Erro: inserção de atributo vazio");
                MensagemUtils.erro(this, "O sistema nao permite valores vazios!", "Erro");
                return;
            } else {
                telaPrincipal.carregarCursos();
                log.info("Curso editado com sucesso, fechando janela...");
                dispose(); 
            }
 
        } catch (RegraNegocioException e) {
            log.error("Erro de validação");
            MensagemUtils.erro(this, e.getMessage(), "Erro de validação");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProfessorProx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCgAnt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProfessorAnt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeAnt = new javax.swing.JTextField();
        txtNomeProx = new javax.swing.JTextField();
        txtCgProx = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR CURSO");
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 40, 30);
        getContentPane().add(txtProfessorProx);
        txtProfessorProx.setBounds(240, 140, 100, 30);

        jLabel2.setText("Carga Horaria ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 80, 30);

        txtCgAnt.setEditable(false);
        txtCgAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCgAntActionPerformed(evt);
            }
        });
        getContentPane().add(txtCgAnt);
        txtCgAnt.setBounds(100, 80, 90, 30);

        jLabel3.setText("Professor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 50, 30);

        txtProfessorAnt.setEditable(false);
        getContentPane().add(txtProfessorAnt);
        txtProfessorAnt.setBounds(100, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText(">");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 140, 20, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText(">");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 20, 20, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText(">");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 80, 20, 32);

        txtNomeAnt.setEditable(false);
        getContentPane().add(txtNomeAnt);
        txtNomeAnt.setBounds(100, 20, 90, 30);
        getContentPane().add(txtNomeProx);
        txtNomeProx.setBounds(240, 20, 100, 30);
        getContentPane().add(txtCgProx);
        txtCgProx.setBounds(240, 80, 100, 30);

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 200, 120, 30);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 220, 40, 20);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 230, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salvarAlteracoes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCgAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCgAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCgAntActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCgAnt;
    private javax.swing.JTextField txtCgProx;
    private javax.swing.JTextField txtNomeAnt;
    private javax.swing.JTextField txtNomeProx;
    private javax.swing.JTextField txtProfessorAnt;
    private javax.swing.JTextField txtProfessorProx;
    // End of variables declaration//GEN-END:variables

}
