/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author User
 */
public class LinhaCursoPanel extends javax.swing.JPanel {

    /**
     * Creates new form LinhaCursoPainel
     */
    public LinhaCursoPanel() {
        initComponents();

        // Remove o BoxLayout e coloca FlowLayout LEFT com gaps de 5px
        this.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 0));

        // (Re) define tamanhos preferidos pequenos, se quiser
        lblCodigo .setPreferredSize(new Dimension(60, 20));
        lblNome   .setPreferredSize(new Dimension(120,20));
        lblCargaH .setPreferredSize(new Dimension(40, 20));
        lblProfessor.setPreferredSize(new Dimension(140, 20)); // antes era 80
        btnEditar.setPreferredSize(new Dimension(50, 25));
        btnRemover.setPreferredSize(new Dimension(60, 25));

        
        // trava a altura do painel exatamente na altura preferida:
        Dimension d = getPreferredSize();
        setPreferredSize( new Dimension(d.width, d.height) );
        setMaximumSize(   new Dimension(d.width, d.height) );

    }

    
    public void setCurso(Curso c) {
    lblCodigo .setText("[" + c.getCodigo() + "]");
    lblNome   .setText(c.getNome());
    lblCargaH  .setText(c.getCargaHoraria() + "");
    lblProfessor.setText(c.getProfessor());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCargaH = new javax.swing.JLabel();
        lblProfessor = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lblCodigo.setText("jLabel1");
        add(lblCodigo);

        lblNome.setText("jLabel2");
        add(lblNome);

        lblCargaH.setText("jLabel1");
        add(lblCargaH);

        lblProfessor.setText("jLabel1");
        add(lblProfessor);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/persistence/images/editIcon.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/persistence/images/removeIcon.png"))); // NOI18N
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        add(btnRemover);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverActionPerformed

    public void adicionarAcaoEditar(ActionListener l) {
        btnEditar.addActionListener(l);
    }

    public void adicionarAcaoRemover(ActionListener l) {
        btnRemover.addActionListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel lblCargaH;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProfessor;
    // End of variables declaration//GEN-END:variables
}
