/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.util.MensagemUtils;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import jakarta.persistence.TypedQuery;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class PesquisarCursoUI extends javax.swing.JDialog {
    
    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("prg03persistence");
    private CursoController controller;
    private JFrame parent;

    /**
     * Creates new form PesquisarCursoUI
     */
    public PesquisarCursoUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.controller = new CursoController();
        this.parent = (JFrame) parent;
        initComponents();
        
        setVisible(true);
    }
    
    private void buscarCursos() {
        String termo = txtCampoPesquisa.getText().trim();
        EntityManager em = emf.createEntityManager();
        try {
            
            List<Curso> resultados = controller.findByNome(termo, parent);

            // Esvazia o JTextArea
            txaResposta.setText("");
            
            if (resultados.isEmpty()) {
                MensagemUtils.info(this, "Nenhum curso encontrado.", "Aviso");
                //txaResposta.setText("Nenhum curso encontrado.");
            } else {
                for (Curso c : resultados) {
                    txaResposta.append("[" + c.getId() + "] " + c.getNome()
                            + " - " + c.getCargaHoraria() + "h - Prof: " + c.getProfessor() + "\n");
                }
            }
        } finally {
            em.close();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCampoPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jspResposta = new javax.swing.JScrollPane();
        txaResposta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome do Curso:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        txtCampoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 280, 30));

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 110, 30));

        txaResposta.setColumns(20);
        txaResposta.setRows(5);
        jspResposta.setViewportView(txaResposta);

        getContentPane().add(jspResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        buscarCursos();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCampoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoPesquisaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jspResposta;
    private javax.swing.JTextArea txaResposta;
    private javax.swing.JTextField txtCampoPesquisa;
    // End of variables declaration//GEN-END:variables
}
