/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.infrastructure.dao.CursoDAO;
import br.com.ifba.curso.infrastructure.entity.Curso;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class TelaCursosUI extends javax.swing.JFrame {
    CursoDAO dao = new CursoDAO();

    /**
     * Creates new form TelaCursosUI
     */
    public TelaCursosUI() {
        initComponents();
        
        // Define layout vertical para o painel interno
        painelInternoCursos.setLayout(new BoxLayout(painelInternoCursos, BoxLayout.Y_AXIS));
        
        carregarCursos();
    }
    
    public void carregarCursos() {
        // Limpa o JPainel que exibe os cursos
        painelInternoCursos.removeAll();
        
        List<Curso> cursos = dao.listarTodos();
        
        for (Curso c : cursos) {
            painelInternoCursos.add(criarLinha(c));
        }
        painelInternoCursos.revalidate();
        painelInternoCursos.repaint();
    }
    
    private JPanel criarLinha(Curso c) {
        JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT));
        linha.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        
        JLabel lblInfo = new JLabel("[" + c.getCodigo() + "] " + c.getNome()
                    + " - " + c.getCargaHoraria() + "h - Prof: " + c.getProfessor());
        linha.add(lblInfo);
        
        // fixa um tamanho para o JLabel
        lblInfo.setPreferredSize(new Dimension(280, 20));
        
        // Cria os botões por linha
        JButton btnRemover = new JButton();
        JButton btnEditar = new JButton();
        
        // Adicionar os icones correspondentes
        btnEditar.setIcon(new ImageIcon(getClass().getResource("/br/com/ifba/persistence/images/editIcon.png")));
        btnRemover.setIcon(new ImageIcon(getClass().getResource("/br/com/ifba/persistence/images/removeIcon.png")));
        
        btnEditar.addActionListener(e -> {
            new EditarCurso(this, c, dao);
            carregarCursos();
        });
        
        btnRemover.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(null,
                    "Tem certeza que deseja remover o curso?",
                    "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                dao.remover(c);
                carregarCursos(); // Atualiza a lista após remover
            }   
        });
        
        linha.add(lblInfo);
        linha.add(btnEditar);
        linha.add(btnRemover);
        
        return linha;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        scrollCursos = new javax.swing.JScrollPane();
        painelInternoCursos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIADOR DE CURSOS");

        btnAdicionar.setText("Adicionar Curso");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnAdicionar);

        btnPesquisar.setText("Pesquisar Curso");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnPesquisar);

        javax.swing.GroupLayout painelInternoCursosLayout = new javax.swing.GroupLayout(painelInternoCursos);
        painelInternoCursos.setLayout(painelInternoCursosLayout);
        painelInternoCursosLayout.setHorizontalGroup(
            painelInternoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        painelInternoCursosLayout.setVerticalGroup(
            painelInternoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        scrollCursos.setViewportView(painelInternoCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCursos))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        AdicionarCursoUI dialog = new AdicionarCursoUI(this, true, dao);
        dialog.setVisible(true);
        carregarCursos();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new PesquisarCurso(this);
        carregarCursos();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCursosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCursosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCursosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCursosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCursosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelInternoCursos;
    private javax.swing.JScrollPane scrollCursos;
    // End of variables declaration//GEN-END:variables
}
