/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.util.MensagemUtils;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author User
 */
public class TelaCursosUI extends javax.swing.JFrame {
    
    private final CursoIController controller;


    /**
     * Creates new form TelaCursosUI
     */
    public TelaCursosUI() {
        this.controller = new CursoController();
        initComponents();
        
        scrollCursos.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

        
        // Define layout vertical para o painel interno
        painelInternoCursos.setLayout(new BoxLayout(painelInternoCursos, BoxLayout.Y_AXIS));
        painelInternoCursos.setPreferredSize(new Dimension(650, painelInternoCursos.getPreferredSize().height));

        
        // força o painel de linhas a usar alinhamento à esquerda
        painelInternoCursos.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        // Altera o Layout para FlowLayout
        painelCabecalho.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 0));

        // Redimensiona cada JLabel (dimensões identicas as linhas)
        lblCabecalhoCodigo.setPreferredSize(new Dimension(60, 20));
        lblCabecalhoNome.setPreferredSize(new Dimension(120, 20));
        lblCabecalhoCarga.setPreferredSize(new Dimension(40, 20));
        lblCabecalhoProfessor.setPreferredSize(new Dimension(140, 20));
        lblEditar.setPreferredSize(new Dimension(50, 20));
        lblRemover.setPreferredSize(new Dimension(60, 20));

        
        carregarCursos();
    }
    
    public void carregarCursos() {
    painelInternoCursos.removeAll();

    List<Curso> cursos = controller.findAll(this);

    for (Curso c : cursos) {
        LinhaCursoPanel linha = new LinhaCursoPanel();
        linha.setCurso(c); // define os dados visuais
        linha.setAlignmentX(Component.LEFT_ALIGNMENT);

        // ação de editar
        linha.adicionarAcaoEditar(e -> {
            new EditarCursoUI(this, c, true);
            carregarCursos();
        });

        // ação de remover
        linha.adicionarAcaoRemover(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (MensagemUtils.confirmar(TelaCursosUI.this, 
                        "Tem certeza que deseja remover o curso?", 
                        "Confirmação")) {
                    // como é um Listener 'this' não representa mais o JFrame, mas sim o contexto de Listener
                    controller.delete(TelaCursosUI.this, c.getId());
                    carregarCursos();
                }   
            }
        });

        painelInternoCursos.add(linha);
    }

        painelInternoCursos.revalidate();
        painelInternoCursos.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        scrollCursos = new javax.swing.JScrollPane();
        painelInternoCursos = new javax.swing.JPanel();
        painelCabecalho = new javax.swing.JPanel();
        lblCabecalhoCodigo = new javax.swing.JLabel();
        lblCabecalhoNome = new javax.swing.JLabel();
        lblCabecalhoCarga = new javax.swing.JLabel();
        lblCabecalhoProfessor = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblRemover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIADOR DE CURSOS");

        btnAdicionar.setText("Adicionar Curso");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnAdicionar);

        btnPesquisar.setText("Pesquisar Curso");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnPesquisar);

        scrollCursos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        painelInternoCursos.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout painelInternoCursosLayout = new javax.swing.GroupLayout(painelInternoCursos);
        painelInternoCursos.setLayout(painelInternoCursosLayout);
        painelInternoCursosLayout.setHorizontalGroup(
            painelInternoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        painelInternoCursosLayout.setVerticalGroup(
            painelInternoCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        scrollCursos.setViewportView(painelInternoCursos);

        lblCabecalhoCodigo.setText("Codigo");

        lblCabecalhoNome.setText("Nome");

        lblCabecalhoCarga.setText("Horas");

        lblCabecalhoProfessor.setText("Professor");

        lblEditar.setText("Editar");

        lblRemover.setText("Remover");

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCabecalhoCodigo)
                .addGap(26, 26, 26)
                .addComponent(lblCabecalhoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCabecalhoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCabecalhoProfessor)
                .addGap(28, 28, 28)
                .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRemover)
                .addGap(31, 31, 31))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCabecalhoCodigo)
                    .addComponent(lblCabecalhoNome)
                    .addComponent(lblCabecalhoCarga)
                    .addComponent(lblCabecalhoProfessor)
                    .addComponent(lblEditar)
                    .addComponent(lblRemover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new AdicionarCursoUI(this, true);
        carregarCursos();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new PesquisarCursoUI(this, true);
        carregarCursos();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    public void lancarMensagem(String mensagem) {
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel lblCabecalhoCarga;
    private javax.swing.JLabel lblCabecalhoCodigo;
    private javax.swing.JLabel lblCabecalhoNome;
    private javax.swing.JLabel lblCabecalhoProfessor;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelInternoCursos;
    private javax.swing.JScrollPane scrollCursos;
    // End of variables declaration//GEN-END:variables
}
